apiVersion: v1
kind: Secret
metadata:
  name: htpass-secret
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/sync-options: Prune=false
    argocd.argoproj.io/compare-options: IgnoreExtraneous
data:
  htpasswd: b2NwLWFkbWluOiQyeSQwNSR6V2hRSU1YY3EzdU9kMmRNOEJDNGJ1aEl1SnpaQk5zaEtXanpxbXoxUkJYRHBEQnFMb3psdQpvY3AtZGV2ZWxvcGVyOiRhcHIxJC82MkRaU3J6JEJ2RmlzeDVGYXZmSVNHQVpCbjdCaTEKb2NwLW1hcmtldGluZzokYXByMSQzTGtJWXdiTyRkRkV4aXhudUxlTnBNc2dPa3Fpck8u
type: Opaque
