apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pricelist-app
spec:
  destination:
    namespace: pricelist
    server: https://kubernetes.default.svc
  project: pricelist
  source:
    path: pricelist/
    repoURL: https://github.com/thoward-rh/gitops-examples
    targetRevision: master
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
